data_path: "data/"
save_path: "output/"
random_seed: 42

# device
# gpu_id: [0]
gpu_id: 0

#dataset
corpus_path: "data/regulations_with_metadata.json"
qa_path: "data/QA_filtered.json"
stopword_path: "data/stopwords.txt"
dict_path: "data/dataset_dict.txt"
bing_api: "63516b23c16b44e4947a5142c58b9292"
bing_url: "https://api.bing.microsoft.com/v7.0/search"
#queryupdate
llm_model: "qwen-max-latest"
base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key: "sk-c02056e042844ee1815cb64d8ede554f"

# database_config
db_name: "my_db"
db_uri: "./milvus.db"
# db_uri: "http://localhost:19530"
db_collection_name: "regulation"
db_output_fields: ["content"]
db_index_fields: ["dense_vector", "sparse_vector"]
db_chunk_size: 256
db_embedding_dim: 1024
db_text_id: "text_id"
db_content_key: "content"
db_appendix_content_key: "appendix_content"
db_metadata_key: "metadata"
db_sparse_index_type: "SPARSE_INVERTED_INDEX"
db_dense_index_type: "HNSW"
# db_dense_index_type: "IVF_FLAT"

# retriever
embedding_model: "BAAI/bge-m3"
retriever_topk: 5
rrf_k: 60
fields_to_search: ["metadata"]
enginesearch_mode: "bing"
# rerank
rerank_model: "BAAI/bge-reranker-v2-m3"
rerank_topk: 3

#generate
generate_model: "Qwen/Qwen2.5-0.5B-Instruct"
generate_config:
  max_length: 1024      # 根据需要调整最大长度
  num_return_sequences: 1
  no_repeat_ngram_size: 2
  top_p: 0.95
  temperature: 0.9
  num_beams: 3
  early_stopping: true
# -------------------------------------------------Evaluation Settings------------------------------------------------#
# Metrics to evaluate the result
metrics:
  [
    "f1",
    "em",
    "bleu",
    "acc",
    "precision",
    "recall",
    "rouge-1",
    "rouge-2",
    "rouge-l",
    "retrieval_recall",
    "retrieval_precision",
  ]
# Specify setting for metric, will be called within certain metrics
metric_setting:
  bleu_max_order: 4
  bleu_smooth: False
  retrieval_recall_topk: 2
  #tokenizer_name: "gpt-4"
save_metric_score: True #　whether to save the metric score into txt file
save_intermediate_data: False
