data_path: "data/"
save_path: "output/"
random_seed: 42

# device
gpu_id: [ 0,1,2,3 ]

#dataset
corpus_path: "data/corpus/dataset.json"
qa_path: "data/corpus/qa.json"

# database_config
db_name: "my_db"
db_uri: "./milvus.db"
db_host: "localhost"
db_port: "19530"
db_collection_name: "CustomRegulations"
db_output_fields: ["content"]
db_index_fields: ["dense_vector","sparse_vector"]
db_chunk_size: 256

# retriever
embedding_model: "BAAI/bge-m3"
retriever_topk: 20
rrf_k: 60

# rerank
rerank_model: "BAAI/bge-reranker-v2-m3"
rerank_topk: 5

#generate
generate_model: "Qwen/Qwen2.5-3B-Instruct"